name: B2C NH UI Selenium Test

on:
  push:
    branches:
      - feature/move-ui-tests-to-github
jobs:
  test_BrowserStack_chrome:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        profile: [schoolqa]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: UI Test
        run: mvn -P${{matrix.profile}} -Dgrid=browserstack -Dbrowser=chrome -Dtest=ChangeCourseTest.java -DprojectName=TwoThread_"${{matrix.profile}}" -DbuildNumber=2001 -DbaseReportDir="target/surefire-reports/" test
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: artifact-test-report-${{matrix.profile}}
          path: target/surefire-reports
      -name: Publish Test Report
       uses: scacap/action-surefire-report@v1
       if: always()
       with:
           github_token:${{ secrets.GITHUB_TOKEN }}

#
# browser: [chrome]
#  test_chrome_bstack:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        chromeBrowserVersion: [79.0, 78.0, 77.0, 63.0]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: UI Test
#        run: mvn -Pb2b_qa -DgridEnvironment=cloud -Dthread.count=1 -DbrowserName=chrome -DbrowserVersion=${{matrix.chromeBrowserVersion}} -Dos="win" -DcloudUser="${{secrets.CLOUD_BS_USERNAME}}" -DcloudAccessKey="${{secrets.CLOUD_BS_ACCESS_KEY}}" clean test
#      - uses: actions/upload-artifact@master
#        if: always()
#        with:
#          name: chrome_artifact-test-report-${{matrix.chromeBrowserVersion}}
#          path: target/surefire-reports
#
#  test_firefox_bstack:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        ffBrowserVersion: ["71.0", "70.0", "64.0"]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: UI Test
#        run: mvn -Pb2b_qa -DgridEnvironment=cloud -Dthread.count=1 -DbrowserName=firefox -DbrowserVersion=${{matrix.ffBrowserVersion}} -Dos="win" -DcloudUser="${{secrets.CLOUD_BS_USERNAME}}" -DcloudAccessKey="${{secrets.CLOUD_BS_ACCESS_KEY}}" clean test
#      - uses: actions/upload-artifact@master
#        if: always()
#        with:
#          name: firefox_artifact-test-report-${{matrix.ffBrowserVersion}}
#          path: target/surefire-reports
#
#  test_safari_bstack:
#    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 1
#      matrix:
#        os: [sierra, mojave, catalina]
#        safriBrowserVersion: ["11", "12", "13"]
#        exclude:
#          # excludes
#          - os: sierra
#            safriBrowserVersion: 12
#          - os: sierra
#            safriBrowserVersion: 13
#          - os: mojave
#            safriBrowserVersion: 11
#          - os: mojave
#            safriBrowserVersion: 13
#          - os: catalina
#            safriBrowserVersion: 11
#          - os: catalina
#            safriBrowserVersion: 12
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: UI Test
#        run: mvn -Pb2b_qa -DgridEnvironment=cloud -Dthread.count=1 -DbrowserName=safari -DbrowserVersion=${{matrix.safriBrowserVersion}} -Dos=${{matrix.os}} -DcloudUser="${{secrets.CLOUD_BS_USERNAME}}" -DcloudAccessKey="${{secrets.CLOUD_BS_ACCESS_KEY}}" clean test
#      - uses: actions/upload-artifact@master
#        if: always()
#        with:
#          name: safari_artifact-test-report-${{matrix.os}}-${{matrix.safriBrowserVersion}}
#          path: target/surefire-reports
#  test_ie_bstack:
#    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 1
#      matrix:
#        os: [win]
#        ieBrowserVersion: ["11"]
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: UI Test
#        run: mvn -Pb2b_qa -DgridEnvironment=cloud -Dthread.count=1 -DbrowserName=ie -DbrowserVersion=${{matrix.ieBrowserVersion}} -Dos=${{matrix.os}} -DcloudUser="${{secrets.CLOUD_BS_USERNAME}}" -DcloudAccessKey="${{secrets.CLOUD_BS_ACCESS_KEY}}" clean test
#      - uses: actions/upload-artifact@master
#        if: always()
#        with:
#          name: safari_artifact-test-report-${{matrix.os}}-${{matrix.ieBrowserVersion}}
#          path: target/surefire-reports